spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ticket_stampede_reservation
spring.datasource.username=ticket_stampede_app
spring.datasource.password=${TICKET_STAMPEDE_DB_PASSWORD}

spring.datasource.hikari.register-mbeans=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true
spring.flyway.clean-disabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

jobrunr.background-job-server.enabled=true
jobrunr.dashboard.enabled=true

ticketstampede.reservation.ttl=10s
ticketstampede.queue.ttl=5m
ticketstampede.payment.failure-probability=0.02
ticketstampede.payment.max-delay-ms=0
