spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ticket_stampede
spring.datasource.username=ticket_stampede_app
spring.datasource.password=${TICKET_STAMPEDE_DB_PASSWORD}
spring.datasource.hikari.register-mbeans=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true
spring.flyway.clean-disabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never